version: '3'
services:
  web:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php-fpm
    links:
      - db
      
  php-fpm:
    image: php:fpm
    container_name: myapp_php
    volumes:
      - .:/var/www/html
  db:
    image: mariadb
    volumes:
      - myapp_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myapp
      MYSQL_INITDB_SKIP_TZINFO: "--max_connections=500"
    command: --max_connections=500 # Set the maximum number of connections
    healthcheck:
      test: ["CMD", "mariadb", "-h", "localhost", "-u", "root", "-proot", "-e", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  myapp_data: # Declare the volume here